# See also https://circleci.com/docs/2.0/language-clojure/
version: 2
jobs:
  build:
    working_directory: ~/hikari-cp
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: nbd
    steps:
      - checkout
      - restore_cache:
          key: hikari-cp-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: hikari-cp-{{ checksum "project.clj" }}
      - run: lein test
